'use client';

import { useState } from 'react';

const products = {
  'Essential Form 01': { price: '৳ 4,900', image: '/look-essential.png', desc: 'Oversized off-white sweatshirt paired with washed wide-leg denim. Relaxed proportion, quiet contrast, everyday structure.' },
  'Leather Structure 02': { price: '৳ 8,900', image: '/look-leather.png', desc: 'Black leather outer layer balanced with a crisp shirt, tie and washed wide denim. Structured, monochrome and deliberate.' },
  'Utility Layer 03': { price: '৳ 5,900', image: '/look-utility.png', desc: 'Layered umber tee over a light base with oversized utility trousers. Functional details kept within a restrained palette.' },
};

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [quick, setQuick] = useState(null);
  const [size, setSize] = useState('M');
  const [bag, setBag] = useState(0);
  const openProduct = (name) => setQuick({ name, ...products[name] });

  return <>
    <div className="frame-label">main page</div>
    <main className="shell">
      <header className="brand-header">
        <a className="logo" href="/" aria-label="MENIMAL home"><img src="/menimal-wordmark.svg" alt="MENIMAL" style={{ width: 'clamp(210px, 18vw, 320px)', height: 'auto', display: 'block' }} /></a>
      </header>
      <section className="hero" id="home"><button className="menu-toggle" aria-label="Open menu" onClick={() => setMenuOpen(true)}><span /></button><div className="hero-right">COLLECTION / 01</div><div className="hero-art"><img src="/40968792190ac710e64bd977657cc25d.jpg" alt="MENIMAL monochrome campaign hero" /></div><div className="hero-copy">Only what matters. <span>— Collection 01</span></div><a className="hero-cta" href="/collection">Explore</a></section>
      <section className="products" id="collection"><div className="section-head"><h2>New Form / 01</h2><a className="view" href="/collection">View collection →</a></div><div className="grid">
        <a className="card" href="/product/essential-form-01"><div className="img"><img src="/look-essential.png" alt="Off-white oversized sweatshirt with washed wide-leg denim" /></div><div className="card-meta"><span className="name">Essential Form 01 / Chalk</span><span className="price">৳ 4,900</span></div></a>
        <article className="card" onClick={() => openProduct('Leather Structure 02')}><div className="img"><img src="/look-leather.png" alt="Black leather jacket with shirt, tie and wide denim" /></div><div className="card-meta"><span className="name">Leather Structure 02 / Black</span><span className="price">৳ 8,900</span></div></article>
        <article className="card" onClick={() => openProduct('Utility Layer 03')}><div className="img"><img src="/look-utility.png" alt="Brown layered tee with black utility trousers" /></div><div className="card-meta"><span className="name">Utility Layer 03 / Umber</span><span className="price">৳ 5,900</span></div></article>
      </div></section>
      <section className="manifesto" id="philosophy"><div className="manifesto-copy"><div className="eyebrow">The principle</div><h2>Details earn<br />their place.</h2><p>MENIMAL is built around reduction, proportion and intent. Every line exists for a reason. Every detail has to justify itself. The result is not absence — it is clarity.</p></div><div className="manifesto-art"><div className="vertical">MENIMAL / SYSTEM 01</div></div></section>
      <section className="lookbook" id="lookbook"><div className="section-head"><h2>Wardrobe System</h2><div className="view">Look 01 — 02</div></div><div className="look-row"><div className="look-large"><img src="/editorial-motion.png" alt="Monochrome movement editorial" /><div className="look-label">Look 04 / Motion without excess</div></div><div className="look-small"><img src="/editorial-grey.png" alt="Grey tonal MENIMAL tailoring" /><div className="look-label">Look 05 / Quiet structure</div></div></div></section>
      <section className="second-sequence" id="details"><div className="section-head"><h2>Material / 02</h2><div className="view">Form — Detail — Scale</div></div><div className="sequence-grid"><div className="sequence-product"><img src="/product-tan.png" alt="Tan MENIMAL short sleeve top" /><div className="sequence-caption">Object 01 / Sand</div></div><div className="sequence-editorial"><img src="/editorial-scale.png" alt="Monochrome oversized footwear editorial" /><div className="sequence-caption">Study 02 / Scale</div></div></div><div className="detail-strip"><figure><img src="/editorial-boots.png" alt="Black leather boots detail" /><figcaption>Detail 01 / Leather</figcaption></figure><figure><img src="/editorial-chair.png" alt="Monochrome footwear editorial on chair" /><figcaption>Detail 02 / Motion</figcaption></figure><figure><img src="/editorial-motion.png" alt="Monochrome body movement editorial" /><figcaption>Detail 03 / Balance</figcaption></figure></div></section>
      <section className="about" id="about"><div className="about-intro"><div><div className="eyebrow">About MENIMAL / 01</div><h2>Nothing<br />without<br />purpose.</h2></div><div><p>MENIMAL is a study in restraint. We build a wardrobe around proportion, movement and material rather than noise. Familiar forms are reduced, rebalanced and made to live together — pieces that hold presence without asking for attention.</p><a href="/about" style={{ display: 'inline-block', marginTop: '24px', borderBottom: '1px solid #111', paddingBottom: '4px', textTransform: 'uppercase', fontSize: '11px', letterSpacing: '.12em' }}>Read our story →</a></div></div><div className="about-gallery"><figure><img src="/editorial-scale.png" alt="Black and white scale editorial" /><figcaption>Scale / Perspective / Form</figcaption></figure><figure><img src="/editorial-chair.png" alt="Black and white seated fashion detail" /><figcaption>Movement / Contrast / 02</figcaption></figure></div><div className="about-principles"><div className="principle"><span>01 / FORM</span><h3>Reduction before decoration.</h3><p>Silhouette comes first. We remove until every remaining line has a reason to stay.</p></div><div className="principle"><span>02 / MATERIAL</span><h3>Texture carries the detail.</h3><p>Weight, hand-feel and construction create character without relying on unnecessary ornament.</p></div><div className="principle"><span>03 / SYSTEM</span><h3>Designed to belong together.</h3><p>Each piece is considered as part of a wider wardrobe — adaptable, repeatable and intentionally quiet.</p></div></div></section>
      <section className="brand-moment"><div className="open-m" aria-label="MENIMAL Open-M icon"><img src="/open-m.svg" alt="MENIMAL Open-M brand mark" style={{ width: '100%', height: '100%', objectFit: 'contain', opacity: 1 }} /></div><div className="caption">MENIMAL — Only what matters.</div><div className="side">OPEN M / BRAND MARK</div></section>
      <footer id="contact"><div className="footer-top"><div><img src="/menimal-wordmark.svg" alt="MENIMAL" style={{width:'160px',height:'auto',display:'block'}} /><p>A wardrobe built with restraint. Designed around form, material and the confidence to remove what does not belong.</p></div><div><div className="footer-title">Explore</div><div className="footer-links"><a href="/collection">Collection</a><a href="#philosophy">Philosophy</a><a href="#lookbook">Wardrobe System</a><a href="#details">Material</a><a href="/about">About</a></div></div><div><div className="footer-title">Journal</div><div className="newsletter"><input aria-label="Email" placeholder="Your email" /><button>→</button></div></div></div><div className="footer-bottom"><span>© 2026 MENIMAL</span><span>ONLY WHAT MATTERS.</span></div></footer>
    </main>
    {menuOpen && <div className="overlay open" onClick={() => setMenuOpen(false)}><aside className="drawer" onClick={(e) => e.stopPropagation()}><button className="close" onClick={() => setMenuOpen(false)}>×</button><img src="/menimal-wordmark.svg" alt="MENIMAL" style={{width:'180px',height:'auto',display:'block',marginBottom:'70px'}} /><a href="/collection">Collection</a><a href="#philosophy" onClick={() => setMenuOpen(false)}>Philosophy</a><a href="#lookbook" onClick={() => setMenuOpen(false)}>Wardrobe</a><a href="#details" onClick={() => setMenuOpen(false)}>Material</a><a href="/about">About</a><a href="#contact" onClick={() => setMenuOpen(false)}>Contact</a><small>Dhaka / 2026</small></aside></div>}
    {quick && <aside className="quick open"><button className="close" onClick={() => setQuick(null)}>×</button><div className="quick-img"><img src={quick.image} alt={quick.name} /></div><h3>{quick.name}</h3><div>{quick.price}</div><p className="quick-copy">{quick.desc}</p><div className="sizes">{['S','M','L','XL'].map((s) => <button key={s} className={size === s ? 'active' : ''} onClick={() => setSize(s)}>{s}</button>)}</div><button className="add" onClick={() => setBag((b) => b + 1)}>Add to bag — {bag}</button></aside>}
  </>;
}
